// Transactions will be created for payments.

const orders = [
  {
    id: 1,
    amount: 450.89,
    description: 'Payment for Birthday and Flyers.',
    date: '2020-05-12',
    company: 'All Stars Print Limited',
    status: 'success',
    channel: 'mobile money',
    providerName: 'Mtn',
    customerAccount: '0548086391',
    reference: 'Payment for shoes',
    currency: 'GHS',
  },
  {
    id: 2,
    amount: 34.4,
    description: 'Payment for Birthday and Flyers.',
    date: '2020-05-12',
    company: 'All Stars Print Limited',
    status: 'success',
    channel: 'mobile money',
    providerName: 'Mtn',
    customerAccount: '0548086391',
    reference: 'Payment for shoes',
    currency: 'GHS',
  },
  {
    id: 3,
    amount: 45.45,
    description: 'Payment for Birthday and Flyers.',
    date: '2020-05-12',
    company: 'All Stars Print Limited',
    status: 'success',
    channel: 'mobile money',
    providerName: 'Mtn',
    customerAccount: '0548086391',
    reference: 'Payment for shoes',
    currency: 'GHS',
  },
  {
    id: 4,
    amount: 90.90,
    description: 'Payment for Cards and Flyers.',
    date: '2020-05-12',
    company: 'All Stars Print Limited',
    status: 'success',
    channel: 'mobile money',
    providerName: 'Mtn',
    customerAccount: '0548086391',
    reference: 'Payment for shoes',
    currency: 'GHS',
  },
  {
    id: 5,
    amount: 200.90,
    description: 'Payment for Cards and Flyers.',
    date: '2020-05-12',
    company: 'All Stars Print Limited',
    status: 'success',
    channel: 'mobile money',
    providerName: 'Mtn',
    customerAccount: '0548086391',
    reference: 'Payment for shoes',
    currency: 'GHS',
  },
  {
    id: 6,
    amount: 120.90,
    description: 'Payment for Cards and Flyers.',
    date: '2020-05-12',
    company: 'All Stars Print Limited',
    status: 'success',
    channel: 'mobile money',
    providerName: 'Mtn',
    customerAccount: '0548086391',
    reference: 'Payment for shoes',
    currency: 'GHS',
  },
  {
    id: 7,
    amount: 400.90,
    description: 'Payment for Stickers.',
    date: '2020-05-12',
    company: 'All Stars Print Limited',
    status: 'success',
    channel: 'mobile money',
    providerName: 'Mtn',
    customerAccount: '0548086391',
    reference: 'Payment for shoes',
    currency: 'GHS',
  },
  {
    id: 8,
    amount: 340.90,
    description: 'Payment for Stickers.',
    date: '2020-05-12',
    company: 'All Stars Print Limited',
    status: 'success',
    channel: 'mobile money',
    providerName: 'Mtn',
    customerAccount: '0548086391',
    reference: 'Payment for shoes',
    currency: 'GHS',
  },
  {
    id: 9,
    amount: 320.90,
    description: 'Payment for Stickers.',
    date: '2020-05-12',
    company: 'All Stars Print Limited',
    status: 'success',
    channel: 'mobile money',
    providerName: 'Mtn',
    customerAccount: '0548086391',
    reference: 'Payment for shoes',
    currency: 'GHS',
  },
  {
    id: 10,
    amount: 111.20,
    description: 'Payment for Stickers.',
    date: '2020-05-12',
    company: 'All Stars Print Limited',
    status: 'success',
    channel: 'mobile money',
    providerName: 'Mtn',
    customerAccount: '0548086391',
    reference: 'Payment for shoes',
    currency: 'GHS',
  },
];

export default orders;
