/**
 * Many jobs can be created together in the same order.
 * An order has many jobs.
 * An order has a transaction id.
 * The Transaction ID shows the transaction that was used to complete the order.
 */
const jobs = [
  {
    id: 1,
    orderID: 2,
    title: 'Title of the job',
    status: 'Pending',
    createdAt: 'Monday, 22nd April 2020',
    jobType: 'Banner',
    labelColor: 'teal',
    cost: 23.90,
  },
  {
    id: 2,
    orderID: 2,
    title: 'Wedding Banner',
    status: 'Completed',
    createdAt: 'Tuesday, 22nd April 2020',
    jobType: 'Sticker',
    labelColor: 'purple',
    cost: 45.89,
  },
  {
    id: 3,
    orderID: 2,
    title: 'Birthday Cards',
    status: 'Rejected',
    createdAt: 'Friday, 2nd April 2020',
    jobType: 'Paper',
    labelColor: 'orange',
    cost: 123.78,
  },
  {
    id: 4,
    orderID: 2,
    title: 'Saloon Banners',
    status: 'Queried',
    createdAt: 'Monday, 9th May 2020',
    jobType: 'Flag',
    labelColor: 'yellow',
    cost: 35.89,
  },
  {
    id: 5,
    orderID: 2,
    title: 'For Sale Sticker',
    status: 'Pending',
    createdAt: 'Wednesday, 7th May 2020',
    jobType: 'Banner',
    labelColor: 'teal',
    cost: 122.90,
  },
  {
    id: 6,
    orderID: 2,
    title: 'Wedding Banner',
    status: 'Completed',
    createdAt: 'Thursday, 3rd May 2020',
    jobType: 'Banner',
    labelColor: 'teal',
    cost: 145.00,
  },
  {
    id: 7,
    orderID: 2,
    title: 'Phone Adevertisement',
    status: 'Completed',
    createdAt: 'Thursday, 1st May 2020',
    jobType: 'Sticker',
    labelColor: 'purple',
    cost: 12.45,
  },
  {
    id: 8,
    orderID: 2,
    title: 'Saloon Banners',
    status: 'Queried',
    createdAt: 'Monday, 9th May 2020',
    jobType: 'Flag',
    labelColor: 'yellow',
    cost: 90.34,
  },
  {
    id: 9,
    orderID: 2,
    title: 'Birthday Cards',
    status: 'Rejected',
    createdAt: 'Friday, 2nd April 2020',
    jobType: 'Paper',
    labelColor: 'orange',
    cost: 800,
  },
  {
    id: 10,
    title: 'Wedding Banner',
    status: 'Completed',
    createdAt: 'Tuesday, 22nd April 2020',
    jobType: 'Sticker',
    labelColor: 'purple',
    cost: 125,
  },
];

export default jobs;
